name: Daily Flight Data Update

on:
  schedule:
    # kasdien 02:00 UTC (04:00 Vilniuje)
    - cron:  '0 2 * * *'
  workflow_dispatch:  # leidžia paleisti rankiniu būdu

jobs:
  update-flights:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install amadeus pandas python-dotenv

      - name: Fetch and update flights CSV
        env:
          AMADEUS_CLIENT_ID: ${{ secrets.AMADEUS_CLIENT_ID }}
          AMADEUS_CLIENT_SECRET: ${{ secrets.AMADEUS_CLIENT_SECRET }}
        run: |
          python fetch_flights.py

      - name: Commit & push updated CSV
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add flights_data.csv
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Daily update: $(date -u +'%Y-%m-%d')"
            git push
          fi
